[Meta]
name = "Sinkhole and Scaffolding"
width = 12
length = 12
cellWidth = 1.0
cellHeight = 1.0
tilemapClass = "game::MoveWeightedTilemap"

[TerrainDefs]
+ = "Grass"        | tint = "4d7d27", walkable = true, height = 0.3
* = "WoodPlatform" | tint = "a87e52", walkable = true, height = 0.2
m = "Mud"          | tint = "5d3712", walkable = true, height = 0.3, cost = 2, mCost = 2
W = "HighWall"     | tint = "515459", height = 2.0
w = "ShortWall"    | tint = "515459", height = 1.0
^ = "Stairs"       | tint = "ffffff", walkable = true, slope = 'n'
v = "Stairs"       | tint = "ffffff", walkable = true, slope = 's'
< = "Stairs"       | tint = "ffffff", walkable = true, slope = 'e'
> = "Stairs"       | tint = "ffffff", walkable = true, slope = 'w'

[ActorDefs]
# B = "game::Barrel"    | height = 0.5, damage = 10
a = "game::Character" | tint = "c44b65", tm = 0, ty = "Archer", dex = 6.0, HP = 1, AR = 7
W = "game::Character" | tint = "4b90c4", tm = 1, ty = "Warrior", maxHP = 25, HP = 2,
A = "game::Character" | tint = "c44b65", tm = 1, ty = "Archer", dex = 6.0, HP = 1, AR = 7

[Terrain:0]
W W W w m m m m w W W W
W W w w + + + + w w W W
W w + + + w . + + + w W
w w + + . . . . + + w w
+ > + . . . . . . + + +
m + . . . . w . . . + m
m + . w . . . . . . < m
+ + + . . . . . . + + +
w w + + . . . . + + w w
W w + + + w . + + + w W
W W w w + + + + w w W W
W W W w m m m m w W W W

[Actors:0]
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . a
W . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . A . . . . . .
. . . . . . . . . . . .

# . . . . . . . . . . . .
# . . . . . B . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . a
# w . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . B . . . . .
# . . . . . . . . . . . .

[Terrain:1]
. . . + . . . . + . . .
. . + + . . . . + + . .
. + . * * * * * * . + .
+ + . . . . * . . . + +
. . * * * * * . . . . .
. . . . . . * * * . . .
. . . * * . . . * * . .
. . . . * * * * * . . .
+ + . . . . * . . . + +
. + . * * * * * * . + .
. . + + . . . . + + . .
. . . + . . . . + . . .

[Actors:1]
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .
. . . . . . . . . . . .

# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . B . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . B . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . . . .
# . . . . . . . . . B . .
# . . . . . . . . . . . .
